### ISSUE TITLE
Suddenly getting Error: Server Error

### ISSUE THREAD

**Issue by sunnyoswalcro** [dawidd6/action-download-artifact#214] opened 2022-12-02 08:55 UTC
+ I checked workflow and artifact exists but still get error. 
+ was working fine till now for so many months. 
+ I don't see any github incident as of now. But i doubt it can be issue on github side. 
+ still posting here if you have any idea .

Logs:
```
Run dawidd6/action-download-artifact@v2.24.0
==> Repository: XXX
==> Artifact name: XXX
==> Local path: ./XXXX
==> Workflow name: XXXX.yaml
==> Workflow conclusion: success
==> Commit: XXX[22](https://github.com/XXX/actions/runs/XXXXX/jobs/XXXXXX#step:8:23)2d20001b51
Error: Server Error
```

**Comment by mjimeneznet** [comment] 2022-12-02 08:58
I'm facing the same issue since today.

**Comment by baparham** [comment] 2022-12-02 09:47
I'm seeing 100% reproduction of this error, in private repos if that data point matters.

I am using commit sha to reference the run:
```
with:
  workflow: <my other workflow.yml>
  commit: ${{ github.sha }}
  workflow_conclusion: success
  name: <artifact-name>
  path: <my output path>
```

**Comment by dawidd6** [comment] 2022-12-02 09:54
```
Fri 02 Dec 10:52:30 ➜  ~  gh api -H "Accept: application/vnd.github+json" /repos/dawidd6/action-download-artifact/actions/workflows/upload.yml/runs | jq
gh: Server Error (HTTP 502)
{
  "message": "Server Error"
}
```

Most likely issue on GitHub's side.

**Comment by baparham** [comment] 2022-12-02 10:46
this seems resolved to me, as of a few minutes ago it's no longer occurring.

**Comment by dawidd6** [comment] 2022-12-02 10:47
Yep, the endpoint seems to be working now. Closing.

**Closed by dawidd6** 2022-12-02 10:47 UTC
