### ISSUE TITLE
Failed to generate URL to download artifact / no artifacts found

### ISSUE THREAD

**Issue by melkin-globant** [dawidd6/action-download-artifact#148] opened 2022-04-11 21:31 UTC
Error: no artifacts found
https://github.com/televisa-univision/content-service-api-ingest/runs/5979168648?check_suite_focus=true

Error: Failed to generate URL to download artifact
https://github.com/televisa-univision/content-metadata-quality-control/runs/5980000576?check_suite_focus=true

These error messages appeared today, we do not know what may be directly affecting the error messages

**Comment by BevanR** [comment] 2022-04-12 04:08
This looks like duplicate of #147

**Closed** 2022-04-12 06:00 UTC
