### ISSUE TITLE
[Feature Request] Add an optional dry-run to only check artifacts availability

### ISSUE THREAD

**Issue by ilyamt-tandemg** [dawidd6/action-download-artifact#143] opened 2022-03-30 21:51 UTC
I am using this action not only to download artifacts for later use but also to check for artifact availability (because if an artifact exists, there is no need to re-create it). It works fine, but I believe that such a use case can be improved in the following way:
- When using this action to test for artifact existence, if an artifact does not exist, which means that we want to build it, the action will fail and print an error to the log. If dry-mode will be enabled, the action will simply set some output variable without failing or printing, resulting in a nicer-looking flow. 
- When using this action to test for artifact existence, if an artifact exists, it will be downloaded and unzipped. If we are only interested to know that this artifact exists in principle, we don't need to wait for the artifact to be downloaded and unzipped. If dry-mode will be enabled, the action on success will simply update some output variable without further actions, resulting in a nicer-looking flow.

**Comment by oblivioncth** [comment] 2022-04-15 22:08
I actually just made a post about this the other day on the github-actions forums to the resounding response of crickets, so I too would be highly interested in a way to check if an artifact is available or not, and use the output of this check for basic branching (likely calling the tested workflow) in a job.

I need to build Qt which can take quite a while on the GitHub hosted runners, but that build will be reused many times over a long period. Currently I have the workflow managing that set to build it on a schedule of 89 days so that it refreshes with the latest settings (if there even are changes), right before the last artifact expires. The problem is that if anything goes wrong with the workflow I have to worry about re-running it manually since the scheduled period will have passed, which becomes further troublesome if the workflow doesn't belong to the default branch because of `workflow_dispatch` limitations.

Having a feature like this would establish a much more concrete dependency between workflows that share artifacts, allowing one to always regenerate an required artifact if its missing.

@ilyamt-tandemg If you don't mind sharing, even though it isn't ideal because the step/job is marked as failed, what do you do currently to make this work with this action? I'm very new to Actions and I was just hoping you could clarify whether the check is just a step or its own job, what statement you use to check for failure of the action, and then confirmation that you're more or less just calling another workflow to create the artifact when this action fails (and then presumably running the action again to actually get the artifact once that's complete?)

**Comment by dawidd6** [comment] 2022-05-04 16:40
Sounds good. Separate issues is the way to go. Just please try to maintain some backward compatibility of possible.

**Comment by daylamtayari** [comment] 2022-05-31 02:27
@dawidd6 Just wanted to check and see if you had had a chance to review that PR I made to resolve this issue?

**Comment by dawidd6** [comment] 2022-05-31 15:59
This is done.

**Closed by dawidd6** 2022-05-31 15:59 UTC
