### ISSUE TITLE
Downloading Artifacts On a reusable workflow seems to break

### ISSUE THREAD

**Issue by Imeguras** [dawidd6/action-download-artifact#229] opened 2023-02-28 11:51 UTC
Here's the setup im using:
it all starts with a main,
```yaml
name: main_wf
on:
  push: 
    branches: [ master, workflow-stuff ]
jobs:
  test-qt-desktop:
    uses: 
      ./.github/workflows/testQTdesktop_wf.yml
    secrets: inherit
```
which then flows to testQTdesktop
```yaml
name: testQTdesktop_wf
on:
  workflow_call:
    inputs:
      suite: 
        required: false
        type: string
jobs: 
  build-qt-desktop:
    uses: ./.github/workflows/buildQmake_wf.yml
    with:
      qmakeflags: "CONFIG+=test"
      binaryfilename: VolanteAlphaQT_testes
  test-qt-desktop:
    needs: [build-qt-desktop]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch artifacts from build-qt-desktop
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: VolanteAlphaQT_testes
      - name: Run tests
        run: cd $GITHUB_WORKSPACE && ./VolanteAlphaQT -platform offscreen
  
```
in the middle a workflow is hit and produces an artifact
```yaml 
name: buildQmake_wf.yml
on: 
  workflow_call:
    inputs:
      qmakeflags:
        required: false
        type: string
      binaryfilename:
        required: true
        type: string      
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: qt6-base-dev qt5-qmake qtbase5-dev libqt6serialport6 libqt6serialport6-dev libqt5serialport5 libqt5serialport5-dev nlohmann-json3-dev socat gengetopt
        version: 1.0
    - name: Build with qmake
      run: /usr/bin/qmake VolanteAlphaQT.pro ${{ inputs.qmakeflags }} && make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.binaryfilename }}
        path: ${{ github.workspace }}/bin/${{ inputs.binaryfilename }}
        if-no-files-found: error
```

The build step runs as it should producing an artifact with the name `VolanteAlphaQT_testes` the thing is the download part results in:
```
Run dawidd6/action-download-artifact@v2
  with:
    github_token: ***
    path: $GITHUB_WORKSPACE
    name: VolanteAlphaQT_testes
    workflow_conclusion: success
    repo: FSIPLEIRIA/volante_alpha_qt
    check_artifacts: false
    search_artifacts: false
    skip_unpack: false
    if_no_artifact_found: fail
==> Repository: FSIPLEIRIA/volante_alpha_qt
==> Artifact name: VolanteAlphaQT_testes
==> Local path: $GITHUB_WORKSPACE
==> Workflow name: 49617406
==> Workflow conclusion: success
==> (found) Run ID: 4285452593
==> (found) Run date: 2023-02-27T18:09:02Z
==> (not found) Artifact: VolanteAlphaQT_testes
==> Found the following artifacts instead:
Error: no artifacts found
```

Am i doing something wrong? Is this behaviour supported by this repo?

**Comment by dawidd6** [comment] 2023-02-28 13:39
Duplicate of https://github.com/dawidd6/action-download-artifact/issues/224

**Closed by dawidd6** 2023-02-28 13:39 UTC

**Comment by Imeguras** [comment] 2023-02-28 13:48
Yes... he didnt provide any code/execution so thats why i created a new issue to avoid being different issues
@dawidd6

**Comment by dawidd6** [comment] 2023-02-28 13:51
So provide those details in a comment on the other issue instead of creating a new one please.

**Comment by Imeguras** [comment] 2023-02-28 13:56
> So provide those details in a comment on the other issue instead of creating a new one please.

alright will do.
